#!/bin/sh
#
# Helper for using the command-line interface of Faux Pas.
# © 2012-2014 Ali Rantakari. All rights reserved.
#

echoerr() { echo "$@" 1>&2; }

APP_BUNDLE_PATH="/Applications/FauxPas.app/Contents/MacOS/Fauxpas"

if [ ! -e "$APP_BUNDLE_PATH" ]; then
    echoerr "Error: Cannot find Faux Pas at: $APP_BUNDLE_PATH"
    exit 1
fi

PROGRAM_NAME=$(basename "$0") "$APP_BUNDLE_PATH" cli "$@"
